# Generated by Django 5.2 on 2025-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="answered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
